export const categoryNames=
[
  "All-Ceramic Crowns",
  "All-On-4",
  "All-On-6",
  "Amalgam Fillings",
  "Anterior Extractions",
  "Apicectomy / Periradicular Surgery",
  "Bad Breath Treatment",
  "Band 1",
  "Band 2",
  "Band 3",
  "Bite Plates And Splints",
  "Bitewing Radiographs",
  "Biopsy",
  "Bleaching Pen",
  "Bone Grafting",
  "Botox",
  "Botox Treatment",
  "Bridge Adjustment",
  "Bridge Cementation",
  "Bridge Fitting",
  "Bridge Prep",
  "Cantilever Bridge",
  "Caries Risk Assessment",
  "Cbct",
  "Cephalometric Radiographs",
  "Ceramic Braces",
  "Ceramic Crown",
  "Ceramic Crowns",
  "Ceramic Inlays/Onlays",
  "Ceramic Veneers",
  "Child Extraction (Milk Tooth)",
  "Children: 10 – 17 Yrs",
  "Children: 2 – 9 Yrs",
  "Children: Under 2 Years",
  "Chin/Jaw Enhancements",
  "Clear Aligners",
  "Clear Aligners:",
  "Combination Braces",
  "Combination Of Treatments",
  "Composite Bonding",
  "Composite Crowns",
  "Composite Fillings",
  "Composite Inlays",
  "Composite Inlays And Onlays",
  "Composite Inlay/Onlay",
  "Composite Onlays",
  "Composite Veneer",
  "Comprehensive Dental Service",
  "Comprehensive Implant Treatment",
  "Cone Beam Ct (Cbct)",
  "Consultations",
  "Consultation",
  "Cosmetic Consultation",
  "Cosmetic Planning",
  "Cosmetic Recontouring",
  "Crown Adjustment",
  "Crown Cementation",
  "Crown Fitting",
  "Crown Lengthening",
  "Crown Preparation",
  "Crowns",
  "Crowns (Unspecified)",
  "Dental Bonding",
  "Dental Extractions",
  "Dental Implant",
  "Dental Implant Consultation",
  "Dental Implant Or Bridge",
  "Dental Imaging",
  "Dental Implants",
  "Dental Jewelry",
  "Dental Planning",
  "Dental Photography",
  "Dental Sealants",
  "Dental Trauma Treatment",
  "Dental Wax-Ups",
  "Denture Repairs And Additions",
  "Dentures",
  "Desensitizing Treatments",
  "Dietary Advice And Counseling",
  "Endodontic Consultation",
  "Endodontic Planning",
  "Endodontics",
  "Emergency Examinations",
  "Emergency Exam",
  "Emergency Orthodontics",
  "Emergency Treatment - Crown",
  "Emergency Treatment - Debonded Crown",
  "Emergency Treatment - Filling",
  "Emergency Treatment - Pain Relief",
  "Emergency Treatment - Temporary",
  "Emergency Treatment - Unspecified",
  "Emergency Treatments",
  "Emergency Treatments - Filling",
  "Emergency Treatments - Pain Relief",
  "Examination (Adult)",
  "Examination And Consultation",
  "Extraction (Anterior)",
  "Extraction (Molar)",
  "Extraction (Premolar)",
  "Extraction (Simple)",
  "Extraction (Surgical)",
  "Extraction (Wisdom Tooth)",
  "Extraction: Permanent Tooth",
  "Extractions",
  "Extractions - Adult Complex",
  "Extractions - Adult Simple",
  "Extractions - Adult Simple Anterior",
  "Extractions - Adult Simple Posterior",
  "Extractions - Adult Complex Anterior",
  "Extractions - Adult Complex Posterior",
  "Extractions - Adult Wisdom Teeth Lower",
  "Extractions - Adult Wisdom Teeth Upper",
  "Extractions - Child Deciduous Teeth",
  "Extractions - Child Permanent Anterior",
  "Extractions - Child Permanent Molar",
  "Extractions - Child Permanent Premolar",
  "Extractions - Deciduous Tooth",
  "Extractions - Permanent Tooth",
  "Extractions (Permanent)",
  "Extractions (Primary)",
  "Facial Aesthetics",
  "Flexible Dentures",
  "Fluoride",
  "Fluoride Treatment",
  "Fissure Sealants",
  "Full Arch Restoration",
  "Full Dentures",
  "Full Mouth Veneers",
  "Functional Appliances",
  "Functional Appliance",
  "Gingivectomy/Gingivoplasty",
  "Glass Ionomer Fillings",
  "Gold Crowns",
  "Gold Inlays",
  "Gold Inlays And Onlays",
  "Gold Inlays",
  "Gold Onlays",
  "Gold Onlays And Inlays",
  "Guided Implant Surgery",
  "Guided Tissue Regeneration",
  "Hygiene Appointments 0-30 Mins",
  "Hygiene Appointments 30-60 Mins",
  "Implant Abutment",
  "Implant Consultation",
  "Implant Healing",
  "Implant Planning",
  "Implant-Retained Dentures",
  "Implant-Supported Bridge",
  "Inlays",
  "Inlay Adjustment",
  "Inlay Cementation",
  "Inlay Prep",
  "Initial Consultation",
  "Inlays/Onlays",
  "Internal Bleaching",
  "Internal Bleaching:",
  "Interceptive Orthodontics",
  "Intraoral Radiograph",
  "Invisalign - Standard",
  "Invisalign - Standard Express",
  "Invisalign - Standard Go",
  "Invisalign - Standard I7",
  "Invisalign - Standard Moderate",
  "Iv Sedation",
  "Laser Periodontal Treatment",
  "Laser Treatments",
  "Lip Enhancements",
  "Lingual Braces",
  "Lingual Braces:",
  "Maryland Bridge",
  "Metal Crowns",
  "Microneedling",
  "Molar",
  "Molar (Endodontic Treatment)",
  "Mouthwashes And Rinses",
  "Multiple Veneers",
  "New Patient Exam (Adult)",
  "New Patient Exam (Adult) With Scale And Polish",
  "New Patient Exam (Adult) With X-Rays",
  "New Patient Examination Child",
  "New Patient Examination (Child)",
  "New Patient Examination (Child) With X-Rays",
  "Nitrous Oxide",
  "Nitrous Oxide Sedation",
  "Non-Surgical Extraction",
  "Non-Surgical Extractions",
  "Non-Surgical Periodontal Treatment",
  "Occlusion Treatment",
  "Onlay Prep",
  "Oral Hygiene Instruction",
  "Oral Sedation",
  "Oral Surgery",
  "Oral Surgery Consultation",
  "Oral Surgery Procedures",
  "Orthodontic Appliances",
  "Orthodontic Adjustment",
  "Orthodontic Emergency",
  "Orthodontic Headgear",
  "Orthodontic Imaging",
  "Orthodontic Planning",
  "Orthodontic Retainer",
  "Orthodontic Surgery",
  "Orthodontic Treatment Phases",
  "Orthodontics",
  "Other",
  "Other Cosmetic Treatments",
  "Other Endodontic Procedures",
  "Other Hygiene Treatments",
  "Other Related Treatments",
  "Other Whitening Treatments",
  "Otc Whitening",
  "Palatal Expanders",
  "Panoramic Radiographs",
  "Partial/Chrome Dentures",
  "Partial/Partial/Chrome Dentures",
  "Periodontal Assessment",
  "Periodontal Assessment / Charting",
  "Periodontal Consultation",
  "Periodontal Flap Surgery",
  "Periodontal Maintenance",
  "Periodontal Planning",
  "Periodontal Plastic Surgery",
  "Periodontal Plastic Surgery Consultation",
  "Periodontal Regeneration",
  "Periodontal Treatment Consultation",
  "Peri-Oral Fillers",
  "Periapical Radiographs",
  "Porcelain Abutment",
  "Porcelain Crowns",
  "Porcelain Fused To Metal (Porcelain Fused To Metal Crown) Crowns",
  "Porcelain Fused To Metal (Porcelain Fused To Metal Crown) Bridge",
  "Porcelain Inlays",
  "Porcelain Inlays And Onlays",
  "Porcelain Inlays/Onlays",
  "Porcelain Onlays",
  "Porcelain Veneers",
  "Porcelain-Fused-To-Metal Crowns",
  "Post And Core Crown",
  "Prefabricated Post And Core",
  "Premolar",
  "Premolar (Endodontic Treatment)",
  "Primary Tooth Extraction",
  "Primary Tooth Restoration",
  "Private Exam (Adult)",
  "Private Exam (Adult) With X-Rays",
  "Profhilo",
  "Pulpal Extirpation",
  "Pulpotomy",
  "Regular Adult Examination",
  "Regular Adult Examination With Scale And Polish",
  "Regular Exam (Adult)",
  "Regular Exam (Adult) With Scale And Polish",
  "Regular Exam (Adult) With X-Rays",
  "Regular Exam (Adult) With X-Rays:",
  "Regular Exam (Child)",
  "Resin-Bonded Bridge",
  "Resin Infiltration",
  "Restorative Consultation",
  "Ridge Augmentation",
  "Root Canal Re-Treatment",
  "Root Canal Re-Treatment With Specialist",
  "Root Canal Treatment / Rct (Incisor/Canine)",
  "Root Canal Treatment / Rct (Incisor/Canine) Or Root Canal Treatment / Rct (Premolar)",
  "Root Canal Treatment / Rct (Molar)",
  "Root Canal Treatment / Rct (Premolar)",
  "Root Canal Treatment / Rct (Unspecified)",
  "Root Canal Treatment / Rct (Unspecified) With Specialist",
  "Root Canal Treatment (Unspecified) With Specialist",
  "Root Canal Treatment With Specialist",
  "Scale And Polish",
  "Six Month Smiles",
  "Simple Extractions",
  "Simple Extraction",
  "Sinus Lift",
  "Skin Boosters",
  "Smilefast",
  "Snoring And Sleep Apnea Devices",
  "Specialist Consultation",
  "Sports Mouthguards",
  "Stainless Steel Crown",
  "Study Models",
  "Surgical/Complex Extractions",
  "Surgical Extractions",
  "Surgical Tooth Extraction",
  "Surgical Tooth Extractions",
  "Surgical/Wisdom Extractions",
  "Surgical Extraction",
  "Surgical Extraction (Root)",
  "Surgical Extraction (Unpecified)",
  "Surgical Extraction/Complex Extraction",
  "Surgical Extraction (Wisdom Tooth)",
  "Tad",
  "Temporary Bridges",
  "Temporary Crown",
  "Temporary Crowns",
  "Temporary Dentures",
  "Temporary Fillings",
  "Tmj Radiograph",
  "Tmj Treatment",
  "Tooth Whitening",
  "Tooth Whitening - Home And In-Office",
  "Tooth Whitening - Home And In-Office:",
  "Tooth Whitening - In-Office",
  "Tooth Whitening Consultation",
  "Tooth Whitening Maintenance",
  "Tooth Whitening Strips",
  "Tooth Whitening Pastes",
  "Traditional Braces",
  "Traditional Fixed Bridge",
  "Veneer Cementation",
  "Volumising Fillers",
  "Whitening Gel",
  "Whitening Maintenance",
  "Whitening Pen",
  "Wisdom Tooth Extractions",
  "Wrinkle Reduction (Doctor)",
  "Wrinkle Reduction (Nurse)",
  "Wrinkle Relaxing Injections",
  "Wrinkle Softening Injectables",
  "Zirconia Bridge",
  "Zirconia Bridges",
  "Zirconia Inlay",
  "Zirconia Inlays",
  "Zirconia Onlay",
  "Zirconia Onlays"
];
