export const categoryNames=
 [
  "Adult New Patient Exam",
  "Adult Simple Extraction",
  "Airflow",
  "All-Ceramic Crowns",
  "All-Ceramic Crowns,Full Dentures,Traditional Fixed Bridge",
  "All-Ceramic Crowns,Single Veneer",
  "All-Ceramic Crowns,Traditional Fixed Bridge",
  "All-On-4",
  "All-On-6",
  "Amalgam Fillings",
  "Anterior Extractions",
  "Anti-Wrinkle Injections",
  "Apicoectomy / Periradicular Surgery",
  "Bad Breath Treatment",
  "Band 1",
  "Band 2",
  "Band 3",
  "Biopsy",
  "Bite Plates And Splints",
  "Bite Plates And Splints,Sports Mouthguards",
  "Bitewing Radiographs",
  "Bitewing Radiographs,Periapical Radiographs",
  "Bleaching Pen",
  "Bone Grafting",
  "Botox",
  "Botox Treatment",
  "Braces",
  "Bridge Adjustment",
  "Bridge Cementation",
  "Bridge Fitting",
  "Bridge Prep",
  "Cantilever Bridge",
  "Caries Risk Assessment",
  "Cbct",
  "Cephalometric Radiographs",
  "Ceramic Braces",
  "Ceramic Crown",
  "Cheek Enhancements",
  "Child Extraction (Milk Tooth)",
  "Children: 10 – 17 Yrs",
  "Children: 2 – 9 Yrs",
  "Children: Under 2 Years",
  "Chin/Jaw Enhancements",
  "Clear Aligners",
  "Combination Braces",
  "Combination Of Treatments",
  "Complex Extraction",
  "Composite Bonding",
  "Composite Crowns",
  "Composite Fillings",
  "Composite Fillings,Root Canal Treatment / Rct (Unspecified),Other",
  "Composite Inlay",
  "Composite Inlay,Gold Inlays",
  "Composite Inlay/Onlay",
  "Composite Onlay",
  "Composite Veneer",
  "Comprehensive Dental Service",
  "Comprehensive Implant Treatment",
  "Cone Beam Ct (Cbct)",
  "Consultation",
  "Conventional Braces",
  "Core Build Up",
  "Cosmetic Consultation",
  "Cosmetic Planning",
  "Cosmetic Recontouring",
  "Crack/Fracture Repair",
  "Crown Adjustment",
  "Crown Cementation",
  "Crown Fitting",
  "Crown Lengthening",
  "Crown Prep, Fitting, And Adjustment",
  "Crown Preparation",
  "Crowns",
  "Deciduous Teeth (Children Baby Teeth)",
  "Dental Bonding",
  "Dental Bonding,Single Veneer",
  "Dental Extractions",
  "Dental Imaging",
  "Dental Implant",
  "Dental Implant Consultation",
  "Dental Implant Or Bridge",
  "Dental Implant, Dental Implant",
  "Dental Impressions",
  "Dental Jewelry",
  "Dental Photography",
  "Dental Planning",
  "Dental Sealants",
  "Dental Trauma Treatment",
  "Dental Wax-Ups",
  "Denture Repairs And Additions",
  "Dentures",
  "Dermal Fillers",
  "Desensitizing Treatments",
  "Dietary Advice And Counseling",
  "Emergency Exam",
  "Emergency Orthodontics",
  "Emergency Treatment",
  "Emergency Treatment - Crown",
  "Emergency Treatment - Debonded Crown",
  "Emergency Treatment - Filling",
  "Emergency Treatment - Pain Relief",
  "Emergency Treatment - Temporary",
  "Endodontic Consultation",
  "Endodontic Planning",
  "Endodontics",
  "Endodontist Consultation",
  "Exam",
  "Examination (Adult)",
  "Examination And Consultation",
  "Extraction",
  "Extraction - Routine",
  "Extraction - Simple",
  "Extraction - Wisdom Tooth",
  "Extraction (Anterior)",
  "Extraction (Molar)",
  "Extraction (Permanent Tooth)",
  "Extraction (Premolar)",
  "Extraction (Simple)",
  "Extraction (Wisdom Tooth)",
  "Extraction Of Difficult Teeth",
  "Extraction Of Teeth",
  "Extraction: Permanent Tooth",
  "Extractions - Adult Complex",
  "Extractions - Adult Complex Anterior",
  "Extractions - Adult Complex Posterior",
  "Extractions - Adult Simple",
  "Extractions - Adult Simple Anterior",
  "Extractions - Adult Simple Posterior",
  "Extractions - Adult Wisdom Teeth Lower",
  "Extractions - Adult Wisdom Teeth Upper",
  "Extractions - Child Deciduous Teeth",
  "Extractions - Child Permanent Anterior",
  "Extractions - Child Permanent Molar",
  "Extractions - Child Permanent Premolar",
  "Extractions - Deciduous Tooth",
  "Extractions - Permanent Tooth",
  "Extractions (Permanent)",
  "Extractions (Primary)",
  "Facial Aesthetics",
  "Fillers",
  "Fissure Sealants",
  "Flexible Dentures",
  "Fluoride",
  "Fluoride Treatment",
  "Full Arch Restoration",
  "Full Dentures",
  "Full Dentures, Partial/Partial/Chrome Dentures",
  "Full Mouth Veneers",
  "Functional Appliance",
  "Gingivectomy/Gingivoplasty",
  "Glass Ionomer Fillings",
  "Gold Crowns",
  "Gold Inlays",
  "Gold Inlays/Onlays",
  "Gold Onlays",
  "Guided Implant Surgery",
  "Guided Tissue Regeneration",
  "Hygiene Appointments 0-30 Mins",
  "Hygiene Appointments 30-60 Mins",
  "Immediate Dentures",
  "Immediate Loading",
  "Implant Abutment",
  "Implant Consultation",
  "Implant Failure",
  "Implant Healing",
  "Implant Impression",
  "Implant Planning",
  "Implant Planning,Invisalign - Standard,Root Canal Treatment / Rct (Unspecified)",
  "Implant-Retained Dentures",
  "Implants",
  "Implant-Supported Bridge",
  "Inhalation Sedation",
  "Initial Consultation",
  "Inlay",
  "Inlay Adjustment",
  "Inlay Cementation",
  "Inlay Prep",
  "Inlays",
  "Inlays/Onlays",
  "Interceptive Orthodontics",
  "Internal Bleaching",
  "Intraoral Radiograph",
  "Invisalign - Standard",
  "Invisalign - Standard Express",
  "Invisalign - Standard Go",
  "Invisalign - Standard I7",
  "Invisalign - Standard Moderate",
  "Iv Sedation",
  "Laser Periodontal Treatment",
  "Laser Treatments",
  "Lingual Braces",
  "Lip Enhancements",
  "Maryland Bridge",
  "Metal Crowns",
  "Microneedling",
  "Molar",
  "Molar (Endodontic Treatment)",
  "Mouthwashes And Rinses",
  "Multiple Veneers",
  "New Patient Exam (Adult)",
  "New Patient Exam (Adult) With Scale And Polish",
  "New Patient Exam (Adult) With X-Rays",
  "New Patient Exam (Child)",
  "New Patient Exam (Child) With X-Rays",
  "Nitrous Oxide",
  "Nitrous Oxide Sedation",
  "Non-Surgical Extraction",
  "Non-Surgical Periodontal Treatment",
  "Occlusion Treatment",
  "Onlay Prep",
  "Oral Hygiene Instruction",
  "Oral Sedation",
  "Oral Surgery",
  "Oral Surgery Consultation",
  "Oral Surgery Procedures",
  "Orthodontic Adjustment",
  "Orthodontic Appliances",
  "Orthodontic Emergency",
  "Orthodontic Headgear",
  "Orthodontic Imaging",
  "Orthodontic Planning",
  "Orthodontic Retainer",
  "Orthodontic Surgery",
  "Orthodontic Treatment Phases",
  "Orthodontics",
  "Other",
  "Other Cosmetic Treatments",
  "Other Endodontic Procedures",
  "Other Hygiene Treatments",
  "Other Procedures",
  "Other Related Treatments",
  "Other Whitening Treatments",
  "Palatal Expanders",
  "Panoramic Radiographs",
  "Panoramic Radiographs, Cephalometric Radiographs",
  "Partial/Chrome Dentures",
  "Partial/Partial/Chrome Dentures",
  "Periapical Radiographs",
  "Periodontal Assessment",
  "Periodontal Assessment / Charting",
  "Periodontal Consultation",
  "Periodontal Flap Surgery",
  "Periodontal Maintenance",
  "Periodontal Planning",
  "Periodontal Plastic Surgery",
  "Periodontal Plastic Surgery Consultation",
  "Periodontal Regeneration",
  "Periodontal Treatment Consultation",
  "Periodontic Or Implant Consultation",
  "Periodontist Consultation",
  "Peri-Oral Fillers",
  "Planned Simple Extraction",
  "Polishing",
  "Porcelain Abutment",
  "Porcelain Crowns",
  "Porcelain Fused To Metal (Porcelain Fused To Metal Crown) Bridge",
  "Porcelain Fused To Metal (Porcelain Fused To Metal Crown) Crowns",
  "Porcelain Fused To Metal Crown",
  "Porcelain Fused To Metal Crown Crowns",
  "Porcelain Inlays",
  "Porcelain Inlays And Onlays",
  "Porcelain Inlays,All-Ceramic Crowns",
  "Porcelain Inlays,Porcelain Onlays,All-Ceramic Crowns",
  "Porcelain Inlays/Onlays",
  "Porcelain Onlays",
  "Porcelain Veneers",
  "Porcelain-Fused-To-Metal (Porcelain Fused To Metal Crown) Crowns",
  "Porcelain-Fused-To-Metal Crowns",
  "Post And Core Crown",
  "Posterior Extractions",
  "Prefabricated Post And Core",
  "Premolar",
  "Premolar (Endodontic Treatment)",
  "Primary Tooth Extraction",
  "Primary Tooth Restoration",
  "Private Exam (Adult)",
  "Private Exam (Adult) With X-Rays",
  "Profhilo",
  "Pulp Capping",
  "Pulpal Extirpation",
  "Pulpotomy",
  "Regular 'Adult Examination' With Scale And Polish",
  "Regular Exam (Adult) With Scale And Polish",
  "Regular Adult Examination",
  "Regular Adult Examination With Scale And Polish",
  "Regular Exam (Adult)",
  "Regular Exam (Adult) With Scale And Polish",
  "Regular Exam (Adult) With X-Rays",
  "Regular Exam (Child)",
  "Resin Infiltration",
  "Resin-Bonded Bridge",
  "Restorative Consultation",
  "Ridge Augmentation",
  "Root Canal Re-Treatment",
  "Root Canal Re-Treatment With Specialist",
  "Root Canal Treatment / Rct (Incisor/Canine)",
  "Root Canal Treatment / Rct (Incisor/Canine) Or Root Canal Treatment / Rct (Premolar)",
  "Root Canal Treatment / Rct (Incisor/Canine) With Specialist",
  "Root Canal Treatment / Rct (Molar)",
  "Root Canal Treatment / Rct (Molar) With Specialist",
  "Root Canal Treatment / Rct (Premolar)",
  "Root Canal Treatment / Rct (Premolar) With Specialist",
  "Root Canal Treatment / Rct (Unspecified)",
  "Root Canal Treatment / Rct (Unspecified) With Specialist",
  "Root Canal Treatment / Rct With Specialist",
  "Root Canal Treatment With Specialist",
  "Simple Extraction",
  "Single Veneer",
  "Sinus Lift",
  "Sinus Lift, Bone Grafting",
  "Six Month Smiles",
  "Skin Boosters",
  "Smilefast",
  "Snoring And Sleep Apnea Devices",
  "Specialist Consultation",
  "Sports Mouthguards",
  "Stainless Steel Crown",
  "Study Models",
  "Supra-Gingival Professional Mechanical Plaque Removal",
  "Surgical Extraction",
  "Surgical Extraction (Root)",
  "Surgical Extraction (Wisdom Tooth)",
  "Surgical Extraction/Complex Extraction",
  "Surgical Orthodontics",
  "Surgical Tooth Extraction",
  "Surgical/Complex Extractions",
  "Surgical/Wisdom Extractions",
  "Tad",
  "Temporary Bridge",
  "Temporary Crown",
  "Temporary Dentures",
  "Temporary Fillings",
  "Tmj Radiograph",
  "Tmj Treatment",
  "Tooth Extraction",
  "Tooth Whitening",
  "Tooth Whitening - Home And In-Office",
  "Tooth Whitening - In-Office",
  "Tooth Whitening, Tooth Whitening - Home And In-Office",
  "Traditional Braces",
  "Traditional Fixed Bridge",
  "Veneer Cementation",
  "Volumising Fillers",
  "Whitening Consultation",
  "Whitening Gel",
  "Whitening Maintenance",
  "Whitening Mouthwash",
  "Whitening Pen",
  "Whitening Strips",
  "Whitening Toothpastes",
  "Wisdom Tooth Extractions",
  "Wrinkle Reduction (Doctor)",
  "Wrinkle Reduction (Nurse)",
  "Wrinkle Relaxing Injections",
  "Zirconia Bridge",
  "Zirconia Inlay",
  "Zirconia Onlay",
];
