export const categoryNames=
 [
  "regular exam (adult)",
  "new patient exam (adult)",
  "emergency treatments",
  "hygiene appointments 30-60 mins",
  "amalgam fillings",
  "composite fillings",
  "root canal treatment / rct (incisor/canine)",
  "root canal treatment / rct (premolar)",
  "root canal treatment / rct (molar)",
  "gold crowns",
  "Porcelain fused to metal (Porcelain fused to metal crown) crowns",
  "ceramic crown",
  "single veneer",
  "traditional fixed bridge",
  "Tooth whitening - in-office",
  "full dentures",
  "partial/partial/chrome dentures",
  "partial/chrome dentures",
  "flexible dentures",
  "extraction",
  "orthodontic retainer",
  "dental implant",
  "implant-supported bridge",
  "panoramic radiographs",
  "orthodontic treatment phases",
  "band 1",
  "band 2",
  "band 3",
  "exam",
  "regular exam (adult) with scale and polish",
  "bitewing radiographs",
  "surgical extraction",
  "airflow",
  "Tooth whitening",
  "new patient examination child",
  "periapical radiographs",
  "cone beam ct (cbct)",
  "other",
  "non-surgical periodontal treatment",
  "dental sealants",
  "glass ionomer fillings",
  "temporary fillings",
  "inlays/onlays",
  "all-ceramic crowns",
  "post and core crown",
  "dental bonding",
  "pulpal extirpation",
  "pulpotomy",
  "root canal treatment / rct (incisor/canine) or root canal treatment / rct (premolar)",
  "non-surgical extraction",
  "apicectomy / periradicular surgery",
  "denture repairs and additions",
  "ridge augmentation",
  "sinus lift",
  "implant-retained dentures",
  "all-on-4",
  "resin-bonded bridge",
  "Invisalign - standard go",
  "Invisalign - standard",
  "clear aligners",
  "functional appliance",
  "ceramic braces",
  "sports mouthguards",
  "bite plates and splints",
  "crown fitting",
  "snoring and sleep apnea devices",
  "root canal treatment / rct (unspecified)",
  "iv sedation",
  "full mouth veneers",
  "root canal re-treatment",
  "new patient exam (adult) with x-rays",
  "periodontal assessment",
  "nitrous oxide sedation",
  "periodontal regeneration",
  "periodontal flap surgery",
  "consultation",
  "braces",
  "orthodontics",
  "composite veneers",
  "implants",
  "bone grafting",
  "Porcelain fused to metal crown",
  "porcelain inlays/onlays",
  "gingivectomy/gingivoplasty",
  "fluoride",
  "fissure sealants",
  "oral sedation",
  "interceptive orthodontics",
  "regular adult examination",
  "emergency exams",
  "porcelain veneers",
  "gold inlays/onlays",
  "composite inlay/onlay",
  "Tooth whitening - home and in-office",
  "hygiene appointments 0-30 mins",
  "cosmetic recontouring",
  "regular exam (adult) with x-rays",
  "cbct",
  "orthodontic planning",
  "implant planning",
  "surgical/complex extractions",
  "dental wax-ups",
  "porcelain inlays",
  "multiple veneers",
  "study models",
  "simple extractions",
  "primary tooth restoration",
  "composite inlay",
  "premolar",
  "molar",
  "emergency treatment - unspecified",
  "simple extraction",
  "desensitizing treatments",
  "gold onlays",
  "periodontal consultation",
  "crown cementation",
  "internal bleaching",
  "stainless steel crown",
  "emergency treatments - unspecified",
  "porcelain onlays",
  "periodontal plastic surgery",
  "whitening consultation",
  "cephalometric radiographs",
  "resin infiltration",
  "all-on-6",
  "implant abutment",
  "temporary crowns",
  "immediate dentures",
  "implant healing",
  "wrinkle reduction (doctor)",
  "wrinkle reduction (nurse)",
  "emergency examinations",
  "periodontal maintenance",
  "crown lengthening",
  "extraction - simple",
  "extraction - surgical",
  "temporary dentures",
  "whitening maintenance",
  "composite onlay",
  "dental photography",
  "gold inlays",
  "oral hygiene instruction",
  "examination and consultation",
  "tooth extraction",
  "Porcelain fused to metal crown crowns",
  "new patient exam (child)",
  "root canal treatment with specialist",
  "lingual braces",
  "composite bonding",
  "extractions",
  "regular adult examination with scale and polish",
  "root canal treatment / rct (unspecified) with specialist",
  "immediate loading",
  "wrinkle relaxing injections",
  "skin boosters",
  "tmj treatment",
  "lip enhancements",
  "cheek enhancements",
  "chin/jaw enhancements",
  "peri-oral fillers",
  "profhilo",
  "microneedling",
  "surgical extractions",
  "new patient exam (adult) with scale and polish",
  "bridge fitting",
  "guided implant surgery",
  "tad",
  "temporary bridge",
  "porcelain crowns",
  "private exam (adult)",
  "private exam (adult) with x-rays",
  "anti-wrinkle injections",
  "dermal fillers",
  "internal bleaching:",
  "emergency exam",
  "regular \"regular exam (adult) with scale and polish\"",
  "emergency orthodontics",
  "palatal expanders",
  "orthodontic surgery",
  "primary tooth extraction",
  "endodontist consultation",
  "periodontist consultation",
  "guided tissue regeneration",
  "emergency treatment - debonded crown",
  "dental implant consultation",
  "orthodontic imaging",
  "airflow ",
  "fillers",
  "children: under 2 years",
  "children: 2 – 9 yrs",
  "children: 10 – 17 yrs",
  "emergency treatment - pain relief",
  "deciduous teeth (children baby teeth)",
  "dental jewelry",
  "emergency treatments - filling",
  "lingual braces:",
  "surgical/wisdom extractions",
  "implant consultation",
  "endodontic consultation",
  "fluoride treatment",
  "functional appliances",
  "specialist consultation",
  "nitrous oxide",
  "laser treatments",
  "porcelain-fused-to-metal (Porcelain fused to metal crown) crowns",
  "inlay cementation",
  "Tooth whitening - home and in-office:",
  "clear aligners:",
  "new patient examination (child)",
  "emergency treatments - pain relief",
  "whitening toothpastes",
  "whitening strips",
  "surgical orthodontics",
  "new patient exam (child) with x-rays",
  "regular exam (child)",
  "crown preparation",
  "regular exam (adult) with x-rays:",
  "conventional braces",
  "biopsy",
  "emergency treatment - crown",
  "orthodontic appliances",
  "emergency treatment - filling",
  "porcelain inlays and onlays",
  "gold onlays and inlays",
  "crown adjustment",
  "inlays",
  "zirconia inlay",
  "pulp capping",
  "laser periodontal treatment",
  "dietary advice and counseling",
  "\"composite inlay,gold inlays\"",
  "implant failure",
  "\"panoramic radiographs,cephalometric radiographs\"",
  "extraction (molar)",
  "extraction (premolar)",
  "extraction (wisdom tooth)",
  "extraction (surgical)",
  "bridge prep",
  "\"root canal treatment / rct (incisor/canine),root canal treatment / rct (premolar)\"",
  "periodontal planning",
  "endodontic planning",
  "cosmetic planning",
  "oral surgery",
  "bridge adjustment",
  "bad breath treatment",
  "implant impression",
  "anterior extractions",
  "posterior extractions",
  "six month smiles",
  "dental extractions",
  "traditional braces",
  "orthodontic emergency",
  "zirconia onlays",
  "extraction of difficult teeth",
  "otc whitening",
  "extraction of teeth",
  "extractions - deciduous tooth",
  "extractions - permanent tooth",
  "intraoral radiograph",
  "surgical extraction/complex extraction",
  "composite inlays and onlays",
  "temporary bridges",
  "whitening gel",
  "dental impressions",
  "root canal treatment / rct with specialist",
  "gold inlays ",
  "maryland bridge",
  "tmj radiograph",
  "Invisalign - standard moderate",
  "Invisalign - standard express",
  "extraction - routine",
  "extraction - wisdom tooth",
  "extractions (primary)",
  "extractions (permanent)",
  "dental trauma treatment",
  "bridge cementation",
  "oral surgery procedures",
  "other procedures",
  "other cosmetic treatments",
  "other hygiene treatments",
  "other endodontic procedures",
  "composite inlays",
  "other whitening treatments",
  "comprehensive dental service",
  "child extraction (milk tooth)",
  "botox",
  "adult simple extraction",
  "adult surgical extraction (simple)",
  "adult surgical extraction (complex)",
  "adult surgical extraction (wisdom tooth)",
  "\"root canal treatment / rct (incisor/canine), root canal treatment / rct (premolar)\"",
  "orthodontic headgear",
  "temporary crown",
  "consultations",
  "premolar (endodontic treatment)",
  "molar (endodontic treatment)",
  "\"crown prep, fitting, and adjustment\"",
  "mouthwashes and rinses",
  "porcelain fused to metal (Porcelain fused to metal crown) bridge",
  "zirconia bridge",
  "periodontal treatment consultation",
  "zirconia bridges",
  "complex extractions",
  "wisdom tooth extractions",
  "orthodontic adjustment",
  "periodontal assessment / charting",
  "extraction (permanent tooth)",
  "surgical extraction (wisdom tooth)",
  "surgical extraction (unspecified)",
  "surgical extraction (root)",
  "other related treatments",
  "initial consultation",
  "cosmetic consultation",
  "polishing",
  "cantilever bridge",
  "root canal re-treatment with specialist",
  "botox treatment",
  "crowns",
  "surgical tooth extractions",
  "tooth extractions",
  "metal crowns",
  "composile fillings",
  "extraction: permanent tooth",
  "whitening pen",
  "endodontics",
  "bleaching pen",
  "regular \"adult examination\" with scale and polish",
  "root canal treatment / rct (incisor/canine) with specialist",
  "root canal treatment / rct (premolar) with specialist",
  "root canal treatment / rct (molar) with specialist",
  "composite onlays",
  "zirconia inlays",
  "composite veneer",
  "surgical tooth extraction",
  "veneer cementation",
  "composite crowns",
  "prefabricated post and core",
  "whitening mouthwash",
  "combination braces",
  "examination (adult)",
  "inlay prep",
  "full arch restoration",
  "porcelain-fused-to-metal crowns",
  "core build up",
  "\"panoramic radiographs, cephalometric radiographs\"",
  "\"dental implant, dental implant\"",
  "\"gold onlays, gold inlays\"",
  "\"full dentures, partial/partial/chrome dentures\"",
  "\"Tooth whitening, Tooth whitening - home and in-office\"",
  "\"sinus lift, bone grafting\"",
  "dental implant or bridge",
  "emergency orthodontics ",
  "adult new patient exam",
  "dental imaging",
  "oral surgery consultation",
  "periodontal plastic surgery consultation",
  "facial aesthetics",
  "\"composite fillings,root canal treatment / rct (unspecified),other\"",
  "\"all-ceramic crowns,full dentures,traditional fixed bridge\"",
  "\"implant planning,Invisalign - standard,root canal treatment / rct (unspecified)\"",
  "\"gold inlays,gold crowns\"",
  "\"porcelain inlays,porcelain onlays,all-ceramic crowns\"",
  "\"all-ceramic crowns,single veneer\"",
  "\"dental bonding,single veneer\"",
  "\"bitewing radiographs,periapical radiographs\"",
  "\"all-ceramic crowns,traditional fixed bridge\"",
  "\"porcelain inlays,all-ceramic crowns\"",
  "\"bite plates and splints,sports mouthguards\"",
  "caries risk assessment",
  "extraction (simple)",
  "restorative consultation",
  "comprehensive implant treatment",
  "planned simple extraction",
  "gold inlays and onlays",
  "wrinkle softening injectables",
  "volumising fillers",
  "periodontic or implant consultation",
  "supra-gingival professional mechanical plaque removal",
  "\"ceramic crown, ceramic crown\"",
  "dentures",
  "extractions - adult simple anterior",
  "extractions - adult simple posterior",
  "extractions - adult complex anterior",
  "extractions - adult complex posterior",
  "extractions - adult wisdom teeth upper",
  "extractions - adult wisdom teeth lower",
  "extractions - child deciduous teeth",
  "extractions - child permanent anterior",
  "extractions - child permanent premolar",
  "extractions - child permanent molar",
  "extractions - adult complex",
  "extractions - adult simple",
  "non-surgical extractions",
  "inlay",
  "smilefast",
  "Invisalign - standard i7",
  "crowns (unspecified)",
  "porcelain abutment",
  "crack/fracture repair",
  "complex extraction",
  "combination of treatments",
  "inhalation sedation",
  "occlusion treatment",
  "extraction (anterior)",
  "onlay prep",
  "inlay adjustment",
  "zirconia onlay",
  "apicoectomy / periradicular surgery",
  "emergency treatment - temporary",
  "dental planning",
];